kind: Deployment
apiVersion: apps/v1
metadata:
  name: messaging-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-backend
  template:
    metadata:
      labels:
        app: messaging-backend
    spec:
      containers:
        - name: messaging-backend
          image: localhost:5000/messaging-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: messaging-backend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31001
  selector:
    app: messaging-backend